version: '3'

services:

# Data bases
   mongo-db:
     image: mongo:4.4
     command: --nojournal
     hostname: mongo-db
     container_name: fiware-mongo
     ports:
       - "27017:27017"
     volumes:
       - db-data:/data/db

# Orion is the context broker
   orion:
     image: fiware/orion:latest
     hostname: orion
     container_name: fiware-orion
     depends_on:
       - mongo-db
     ports:
       - "1026:1026"
     command: -dbhost mongo-db

# Persistent Data
   fiware-sth-comet:
     image: fiware/sth-comet
     hostname: sth-comet
     container_name: fiware-sth-comet
     depends_on:
       - mongo-db
     ports:
       - "8666:8666"
     environment:
       - STH_HOST=0.0.0.0
       - STH_PORT=8666
       - DB_PREFIX=sth_
       - DB_URI=mongo-db:27017
       - LOGOPS_LEVEL=DEBUG

# MQTT Broker
   mosquitto:
     image: eclipse-mosquitto:latest
     hostname: mosquitto
     container_name: fiware-mosquitto
     expose:
       - "1883"
       - "9001"
     ports:
       - "1883:1883"
       - "9001:9001"
     volumes:
       - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

# MQTT Broker to NGSI
   iot-agent:
     image: fiware/iotagent-ul:latest
     hostname: iot-agent
     container_name: fiware-iot-agent
     depends_on:
       - mongo-db
       - mosquitto
     expose:
       - "4041"
     ports:
       - "4041:4041"
     environment:
       - IOTA_CB_HOST=orion
       - IOTA_CB_PORT=1026
       - IOTA_NORTH_PORT=4041
       - IOTA_REGISTRY_TYPE=mongodb
       - IOTA_LOG_LEVEL=DEBUG
       - IOTA_TIMESTAMP=true
       - IOTA_CB_NGSI_VERSION=v2
       - IOTA_AUTOCAST=true
       - IOTA_MONGO_HOST=mongo-db
       - IOTA_MONGO_PORT=27017
       - IOTA_MONGO_DB=iotagentul
       - IOTA_AMQP_DISABLED=true
       - IOTA_PROVIDER_URL=http://iot-agent:4041
       - IOTA_DEFAULT_RESOURCE=
       - IOTA_DEFAULT_KEY=fatecmeshiot
       - IOTA_MQTT_HOST=mosquitto
       - IOTA_MQTT_PORT=1883
       
volumes:
   db-data:
  
